### ISSUE TITLE
[staging] Database connection goes away

### ISSUE THREAD

**Issue by sherlockwisdom** [smswithoutborders/SMSWithoutBorders-BE-Publisher#3]
When a singleton object is created and reused in the code the error shows up after every transaction

[staging] peewee.OperationalError: (2006, 'MySQL server has gone away')

I think the connection needs to have a dynamic of checking and reopening closed connection.

Other possibilities involve creating the connection at every API call - would go with that while pending more feedback

**Comment by PromiseFru** [comment]
> When a singleton object is created and reused in the code the error shows up after every transaction
> 
> [staging] peewee.OperationalError: (2006, 'MySQL server has gone away')
> 
> I think the connection needs to have a dynamic of checking and reopening closed connection.
> 
> Other possibilities involve creating the connection at every API call - would go with that while pending more feedback

Ah yes I think Peewee mentioned this behavior [here](http://docs.peewee-orm.com/en/latest/peewee/database.html#error-2006-mysql-server-has-gone-away). The database connection will have to be closed after every query.
